# config.yaml
# --- Centralized Configuration for the Polymer Simulation Experiment ---

# --- 1. Run Parameters: Initial conditions and goals ---
run_parameters:
  l_chain: 100
  n_chain: 50
  total_simulation_time: 864000 # in seconds (e.g., 10 days)
  target_properties:
    target_crosslink_density: 0.1
    crosslink_tolerance: 0.02
  param_bounds:
    dose_rate: [0.0, 10.0] # Min and Max dose rate

# --- 2. Model Selection: Choose the simulation engine ---
model_selection:
  # Model 'A': Original graph-based model (deprecated)
  # Model 'B': Kinetics-driven ODE model
  model: 'B'

# --- 3. RL Hyperparameters: SAC agent and training loop ---
rl_hyperparameters:
  learning_rate: 3e-4
  buffer_size: 1000000
  batch_size: 256
  gamma:
    default: 0.99
    min: 0.9
    max: 0.999
  tau:
    default: 0.005
    min: 0.001
    max: 0.02
  alpha:
    default: 0.2
    min: 0.1
    max: 0.3
  max_action: 1.0
  state_dim: 2
  action_dim: 2
  # DSAC parameters
  num_atoms: 51
  v_min: -100.0
  v_max: 0.0
  network_architecture:
    actor: [256, 256]
    critic: [256, 256]
  # Optuna settings
  enable_optuna: true
  optuna_trials: 100
  episodes: 1000
  checkpoint_frequency: 50

# --- 4. Physics Parameters: Constants for the simulation model ---
physics_parameters:
  # Parameters for Model B (Kinetics-Driven)
  # Can be defined inline or as a path to a separate file
  kinetic_rate_constants_path: "kinetic_params.yaml"
  initial_concentrations:
    PE: 22.7
    O2: 0.009
    PE_rad: 0.0
    PEOO_rad: 0.0
    PEOOH: 0.0
    PEOOPE: 0.0
    PECOOH: 0.0
  grid_dimensions: [10, 10, 10]
  voxel_size: 1.0 # nm
  simulation_box_size: [10.0, 10.0, 10.0] # nm (should be grid_dimensions * voxel_size)
  time_step: 3600 # s

# --- 5. Output Paths: Where to save results ---
output_paths:
  database_path: "results/simulation_data.db"
  plot_path: "results/plots/"
  model_path: "results/models/"