# config.yaml
# --- Centralized Configuration for the Polymer Simulation Experiment ---

# --- 1. Run Parameters: Initial conditions and goals ---
run_parameters:
  l_chain: 100
  n_chain: 10
  total_simulation_time: 10000 # in timesteps
  target_properties:
    target_crosslink_density: 0.1
    crosslink_tolerance: 0.02
  param_bounds:
    temperature: [200.0, 400.0]

# --- 2. RL Hyperparameters: SAC agent and training loop ---
rl_hyperparameters:
  learning_rate: 3e-4
  buffer_size: 1000000
  batch_size: 256
  gamma:
    default: 0.99
    min: 0.9
    max: 0.999
  tau:
    default: 0.005
    min: 0.001
    max: 0.02
  alpha:
    default: 0.2
    min: 0.1
    max: 0.3
  max_action: 1.0
  state_dim: 2
  action_dim: 2
  # DSAC parameters
  num_atoms: 51
  v_min: -100.0
  v_max: 0.0
  network_architecture:
    actor: [256, 256]
    critic: [256, 256]
  # Optuna settings
  enable_optuna: true
  optuna_trials: 100
  episodes: 1000
  checkpoint_frequency: 50

# --- 3. LAMMPS Parameters: Settings for the simulation ---
lammps_parameters:
  input_data_path: "data/pe_system.data"
  input_script_path: "data/pe_system.in"
  log_path: "data/pe_system.log"
  executable_path: "lammps" # Assumes lammps is in the system PATH

# --- 4. Output Paths: Where to save results ---
output_paths:
  database_path: "results/simulation_data.db"
  plot_path: "results/plots/"
  model_path: "results/models/"

# --- 5. Script Paths: Locations of executable scripts ---
script_paths:
  md_setup: "scripts/setup_md_system.py"
  reactive_md: "scripts/run_reactive_md.py"
  rl_fine_tuning: "fine_tune_model.py"
